version: "3"
services:
  lab:
    image: jupyter_fswnet:v01 
    container_name: fswnet_container 
    build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile

    ports:
      - "8801:8888"

    volumes:
      - .:/home/jovyan/work

    command: start.sh jupyter lab